version: '3'

services:
    api:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
            - ~/.aws/:/root/.aws:ro
        environment:
          - AWS_REGION=us-east-1
          - BUCKET_NAME=sa-practice-bucket
        ports:
            - 80:80
        tty: true
